root: true
parser: '@typescript-eslint/parser'
env:
  node: true

plugins:
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier

rules:
  array-callback-return: error
  camelcase: error
  consistent-return: 0
  eqeqeq: [error, always, 'null': ignore]
  no-constant-condition: [error, checkLoops: false]
  no-control-regex: 0
  no-fallthrough: [error, commentPattern: fallthrough]
  no-implicit-globals: error
  no-template-curly-in-string: warn
  no-var: error
  prefer-const: [warn, destructuring: all]
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/no-unused-vars': [warn, argsIgnorePattern: '^_']

overrides:
  - files: [tests/**]
    env:
      jest: true
    rules:
      camelcase: 0
