name: JSR Publish

permissions:
  contents: read
  id-token: write

on:
  push:
    tags:
      - v2.*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish
