name: JSR Publish

permissions:
  contents: read
  id-token: write

on:
  push:
    tags:
      - v2.*
      - v3.*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync version to jsr.jsonc
        run: |
          node -e '
            const fs = require("fs");
            const pkgVersion = require("./package.json").version;
            let text = fs.readFileSync("jsr.jsonc", "utf8");

            text = text.replace(
              /(?<="version"\s*:\s*")[^"]+/,
              pkgVersion
            );

            fs.writeFileSync("jsr.jsonc", text);
          '
      - run: npx jsr publish
